import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

public class Test {

    private static double money =0.0;

    public static void main(String[] args) {

        String price ="1.49";
        Set<String> items = new HashSet<>();

        items.add("20 Quarter Pound ");
        items.add("A Taste Of Thai ");
        items.add("A Taste Of Thai ");
        items.add("A1");
        items.add("Activia ");
        items.add("Activia ");
        items.add("Activia ");
        items.add("Activia ");
        items.add("Activia ");
        items.add("Activia ");
        items.add("Activia ");
        items.add("Activia ");
        items.add("Activia ");
        items.add("Activia ");
        items.add("Activia ");
        items.add("Against The Grain Gourmet ");
        items.add("Ah-So");
        items.add("Ah-So");
        items.add("Air Heads");
        items.add("Albanese");
        items.add("ALEIAs ");
        items.add("ALEIAs ");
        items.add("Alfresco ");
        items.add("Alfresco ");
        items.add("Alfresco ");
        items.add("Alfresco ");
        items.add("Alfresco ");
        items.add("Alfresco ");
        items.add("Alfresco ");
        items.add("Alfresco ");
        items.add("Alfresco ");
        items.add("Alfresco ");
        items.add("Alfresco ");
        items.add("Alfresco ");
        items.add("Alfresco ");
        items.add("Alfresco ");
        items.add("Almond joy");
        items.add("Alssi ");
        items.add("American Flatbread ");
        items.add("American Flatbread ");
        items.add("American Flatbread ");
        items.add("American Flatbread ");
        items.add("American Flatbread ");
        items.add("American Flatbread ");
        items.add("Amy's ");
        items.add("Amy's ");
        items.add("Amy's ");
        items.add("Amy's ");
        items.add("Amy's ");
        items.add("Amy's ");
        items.add("Amy's ");
        items.add("Amy's ");
        items.add("Amy's ");
        items.add("Amy's ");
        items.add("Amy's ");
        items.add("Amy's ");
        items.add("Amy's ");
        items.add("Amy's ");
        items.add("Amy's ");
        items.add("Andrew & Everett");
        items.add("Annie Chuns ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Annie's ");
        items.add("Applegate ");
        items.add("Applegate ");
        items.add("Applegate ");
        items.add("Applegate ");
        items.add("Applegate ");
        items.add("Applegate ");
        items.add("Applegate ");
        items.add("Applegate ");
        items.add("Applegate ");
        items.add("AriZona");
        items.add("AriZona");
        items.add("AriZona");
        items.add("AriZona");
        items.add("AriZona");
        items.add("AriZona");
        items.add("AriZona");
        items.add("AriZona");
        items.add("AriZona");
        items.add("AriZona");
        items.add("AriZona");
        items.add("AriZona");
        items.add("AriZona");
        items.add("AriZona");
        items.add("AriZona");
        items.add("AriZona");
        items.add("AriZona");
        items.add("AriZona");
        items.add("Asian Fusion ");
        items.add("Asian Fusion ");
        items.add("Asian Fusion ");
        items.add("Asian Fusion ");
        items.add("Assi");
        items.add("Authenic ");
        items.add("B&G ");
        items.add("Bacardi Mixers ");
        items.add("Bacardi Mixers ");
        items.add("Bacardi Mixers ");
        items.add("Ball Park ");
        items.add("Ball Park ");
        items.add("Ball Park ");
        items.add("Ball Park ");
        items.add("Bar Harbor ");
        items.add("Bar Harbor ");
        items.add("Bar Harbor ");
        items.add("Bar S ");
        items.add("Bar S ");
        items.add("Bar S ");
        items.add("Barbaras");
        items.add("Barbaras");
        items.add("Barbaras");
        items.add("Barbaras");
        items.add("Barbaras");
        items.add("Barbaras");
        items.add("Barbaras");
        items.add("Barer's Joy ");
        items.add("Bark Thins");
        items.add("Bark Thins");
        items.add("Bark Thins");
        items.add("Barney ");
        items.add("Bear Naked ");
        items.add("Bear Naked ");
        items.add("Bear Naked ");
        items.add("Bear Naked ");
        items.add("Bear Naked ");
        items.add("Bear Naked ");
        items.add("Bear Naked ");
        items.add("Bear Naked ");
        items.add("Benihana ");
        items.add("Benihana ");
        items.add("Benihana ");
        items.add("Benihana ");
        items.add("Benissima");
        items.add("Bertolli ");
        items.add("Bertolli ");
        items.add("Bertolli ");
        items.add("Bertolli ");
        items.add("Beyond Meat ");
        items.add("Biazoo");
        items.add("Bibigo");
        items.add("Bibigo");
        items.add("Bibigo");
        items.add("Bibigo");
        items.add("Billybee");
        items.add("Biotta");
        items.add("Birch Benders");
        items.add("Black Forest ");
        items.add("Black Lable ");
        items.add("Blue Diamond ");
        items.add("Blue Diamond ");
        items.add("Blue Diamond ");
        items.add("Blue Diamond ");
        items.add("Boboli ");
        items.add("Boboli ");
        items.add("Body Fortress ");
        items.add("Body Fortress ");
        items.add("Body Fortress ");
        items.add("Body Fortress ");
        items.add("Body Armor");
        items.add("Body Armor");
        items.add("Body Armor");
        items.add("Body Armor");
        items.add("Body Armor");
        items.add("Body Armor");
        items.add("Body Armor");
        items.add("Body Armor");
        items.add("Body Armor");
        items.add("Body Armor");
        items.add("Body Armor");
        items.add("Body Armor");
        items.add("Body Armor");
        items.add("Body Armor");
        items.add("Body Armor");
        items.add("Body Armor");
        items.add("Bombay Market");
        items.add("Botticelli ");
        items.add("Botticelli ");
        items.add("Botticelli ");
        items.add("Bragg ");
        items.add("Bragg ");
        items.add("Bragg ");
        items.add("Bragg ");
        items.add("Bragg ");
        items.add("Bragg ");
        items.add("Bragg ");
        items.add("Braswell's");
        items.add("Breakstone's ");
        items.add("Breakstone's ");
        items.add("Breakstone's ");
        items.add("Breakstone's ");
        items.add("Breath Savers");
        items.add("Brekki ");
        items.add("Brekki ");
        items.add("Brekki ");
        items.add("Brekki ");
        items.add("Brekki ");
        items.add("Brekki ");
        items.add("Brekki ");
        items.add("Briannas ");
        items.add("Briannas ");
        items.add("Briannas ");
        items.add("Briannas ");
        items.add("Briannas ");
        items.add("Briannas ");
        items.add("Briannas ");
        items.add("Briannas ");
        items.add("Briannas ");
        items.add("Briannas ");
        items.add("Briannas ");
        items.add("Briannas ");
        items.add("Briannas ");
        items.add("Bridgford ");
        items.add("Bridgford ");
        items.add("Bridgford ");
        items.add("Bridgford ");
        items.add("Bridgford ");
        items.add("Brown Cow ");
        items.add("Brown Cow ");
        items.add("Brown Cow ");
        items.add("Brown Cow ");
        items.add("Bubba Burger ");
        items.add("Bubba Burger ");
        items.add("Bubba Burger ");
        items.add("Bubble gum");
        items.add("Bubs Naturals");
        items.add("Bubs Naturals");
        items.add("Buddy Fruits");
        items.add("Buddy Fruits");
        items.add("Buddy Fruits");
        items.add("Buitoni ");
        items.add("Buitoni ");
        items.add("Buitoni ");
        items.add("Buitoni ");
        items.add("Buitoni ");
        items.add("Buitoni ");
        items.add("Buitoni ");
        items.add("Buitoni ");
        items.add("Buitoni ");
        items.add("Buitoni ");
        items.add("Buitoni ");
        items.add("Buitoni ");
        items.add("Bulletproof ");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's");
        items.add("Bush's ");
        items.add("Butcher Block Sauces");
        items.add("Butcher Block Sauces");
        items.add("Cains ");
        items.add("Cains ");
        items.add("Cains ");
        items.add("Cains ");
        items.add("Cains ");
        items.add("Cains ");
        items.add("Cains ");
        items.add("CALIFIA");
        items.add("California Olive Ranch");
        items.add("California Olive Ranch");
        items.add("California Olive Ranch");
        items.add("California Olive Ranch");
        items.add("Campbells");
        items.add("Campbells");
        items.add("Cap'n Crunch's");
        items.add("Cap'n Crunch's");
        items.add("Cap'n Crunch's");
        items.add("Cape Code Cafe ");
        items.add("Cape Code Cafe ");
        items.add("Caprisun ");
        items.add("Caprisun ");
        items.add("Caprisun ");
        items.add("Caprisun ");
        items.add("Caprisun ");
        items.add("Caprisun ");
        items.add("Caprisun ");
        items.add("Caprisun ");
        items.add("Caprisun ");
        items.add("Caprisun ");
        items.add("Caprisun ");
        items.add("Caprisun ");
        items.add("Caramel Creams");
        items.add("Carando ");
        items.add("Carando ");
        items.add("Carando ");
        items.add("Carmela");
        items.add("Carnation");
        items.add("Carnation");
        items.add("Carnation");
        items.add("Carnation");
        items.add("Carnation");
        items.add("Carnation");
        items.add("Carolina ");
        items.add("Carolina ");
        items.add("Carolina ");
        items.add("Carolina ");
        items.add("Carolina ");
        items.add("Carolina ");
        items.add("Carolina ");
        items.add("Carolina ");
        items.add("Carolina ");
        items.add("Carolina ");
        items.add("Carolina ");
        items.add("Carolina ");
        items.add("Carolina ");
        items.add("Carrington Frams ");
        items.add("Casa Visco ");
        items.add("Casa Visco ");
        items.add("Cascadian Farm ");
        items.add("Cascadian Farm ");
        items.add("Cascadian Farm ");
        items.add("Cascadian Farm ");
        items.add("Cascadian Farm ");
        items.add("Cascadian Farm ");
        items.add("Caulipower ");
        items.add("Caulipower ");
        items.add("Caulipower ");
        items.add("Caulipower ");
        items.add("Celentano");
        items.add("Celeste ");
        items.add("Celeste ");
        items.add("Celeste ");
        items.add("Celeste ");
        items.add("Celeste ");
        items.add("Celeste ");
        items.add("Chalk Market & Label Set ");
        items.add("Charleston");
        items.add("Chelsea");
        items.add("Cherribundi");
        items.add("Cherribundi");
        items.add("Chocolove");
        items.add("Chocolove");
        items.add("Chocolove");
        items.add("Cholula ");
        items.add("Cholula ");
        items.add("Cholula ");
        items.add("Chosen Foods");
        items.add("Christe's ");
        items.add("Christe's ");
        items.add("Christe's ");
        items.add("Claeys");
        items.add("Clif");
        items.add("Clif");
        items.add("Clif");
        items.add("Clif");
        items.add("Clif");
        items.add("Clif");
        items.add("Clif");
        items.add("Clif");
        items.add("Clif");
        items.add("Clif");
        items.add("Clif");
        items.add("Clif");
        items.add("Clif");
        items.add("Clif");
        items.add("Clif");
        items.add("Clif");
        items.add("Clio ");
        items.add("Clio ");
        items.add("Clio ");
        items.add("Clio ");
        items.add("Coconut Aminos ");
        items.add("Coconut Secret");
        items.add("Cole's");
        items.add("Cole's");
        items.add("Cole's");
        items.add("Cole's");
        items.add("Cole's");
        items.add("Cole's");
        items.add("Colman");
        items.add("Colman");
        items.add("Colman");
        items.add("Colman's ");
        items.add("Colman's ");
        items.add("Colman's ");
        items.add("Colonna ");
        items.add("Columela ");
        items.add("Conte's");
        items.add("Conte's");
        items.add("Cool Whip ");
        items.add("Cool Whip ");
        items.add("Cool Whip ");
        items.add("Cool Whip ");
        items.add("CoraBella");
        items.add("CoraBella");
        items.add("Country Kitchen");
        items.add("Country Kitchen");
        items.add("Country Kitchen");
        items.add("Country Kitchen");
        items.add("Country Kitchen");
        items.add("Country Kitchen");
        items.add("Country Kitchen");
        items.add("Country Kitchen");
        items.add("Country Kitchen");
        items.add("Cow Tales");
        items.add("Crazy Richardy's");
        items.add("Cream of Rice");
        items.add("Cream of Rice");
        items.add("Cream of Wheat ");
        items.add("Cream of Wheat ");
        items.add("Cream of Wheat ");
        items.add("Cream of Wheat ");
        items.add("Cream of Wheat ");
        items.add("Cream of Wheat ");
        items.add("Crofter's");
        items.add("Crofter's");
        items.add("Crofter's");
        items.add("Crofter's");
        items.add("Crosse & BlackWell");
        items.add("Crosse & BlackWell");
        items.add("Crosse & BlackWell");
        items.add("Crosse & BlackWell");
        items.add("Crosse & BlackWell");
        items.add("Cucina and Amore");
        items.add("Cucina and Amore");
        items.add("Cucina and Amore");
        items.add("Cucina and Amore");
        items.add("Cucina and Amore");
        items.add("Dai Day ");
        items.add("Dai Day ");
        items.add("Darrell Sea");
        items.add("DAVIO'S");
        items.add("De Wafelbakkers ");
        items.add("De Wafelbakkers ");
        items.add("De Wafelbakkers ");
        items.add("De Wafelbakkers ");
        items.add("DeIORIO'S");
        items.add("Del monte");
        items.add("Del monte");
        items.add("Del monte");
        items.add("Del monte");
        items.add("Deming's ");
        items.add("Deming's ");
        items.add("Denture ice");
        items.add("Destination ");
        items.add("Deutschamcher ");
        items.add("Deutschamcher ");
        items.add("Devour");
        items.add("Devour");
        items.add("Devour");
        items.add("Devour");
        items.add("Devour");
        items.add("Devour");
        items.add("Devour");
        items.add("Devour");
        items.add("Dicrinson's");
        items.add("Dicrinson's");
        items.add("Dicrinson's");
        items.add("Divine ");
        items.add("Divine ");
        items.add("Divine ");
        items.add("Don Lee Farms ");
        items.add("Don Pepimo");
        items.add("Dr.Praeger's");
        items.add("Dr.Praeger's");
        items.add("Dr.Praeger's");
        items.add("Dr.Praeger's");
        items.add("Dromedary ");
        items.add("Dubble Bubbles ");
        items.add("Dum.Dums");
        items.add("Dutch Colony ");
        items.add("Dynasty");
        items.add("Eckrich");
        items.add("Eckrich ");
        items.add("Eckrich ");
        items.add("Ellio's ");
        items.add("Ellio's ");
        items.add("Ellio's ");
        items.add("Ellio's ");
        items.add("Emperor");
        items.add("Endangered Species");
        items.add("Endangered Species");
        items.add("Endangered Species");
        items.add("Endangered Species");
        items.add("Endangered Species");
        items.add("Evergreen Leaves Brand");
        items.add("Evol ");
        items.add("Explore Cusine");
        items.add("Explore Cusine");
        items.add("Explore Cusine");
        items.add("Fage ");
        items.add("Fage ");
        items.add("Fage ");
        items.add("Fage ");
        items.add("Fage ");
        items.add("Fage ");
        items.add("Fage ");
        items.add("Fage ");
        items.add("Fage ");
        items.add("Familia");
        items.add("Familia");
        items.add("Fanny  ");
        items.add("Fanny  ");
        items.add("Farm Valley");
        items.add("Felix ");
        items.add("Ferrero Rocher");
        items.add("Field Roast  ");
        items.add("Field Roast  ");
        items.add("Field Roast  ");
        items.add("Field Roast  ");
        items.add("Fisherboy");
        items.add("Floridas Natural");
        items.add("Floridas Natural");
        items.add("Floridas Natural");
        items.add("Floridas Natural");
        items.add("Floridas Natural");
        items.add("Floridas Natural");
        items.add("Fontanini");
        items.add("Forager ");
        items.add("Forager ");
        items.add("Forager ");
        items.add("Forager ");
        items.add("Forager ");
        items.add("Forno De Minas");
        items.add("Forno De Minas");
        items.add("French's ");
        items.add("French's ");
        items.add("French's ");
        items.add("French's ");
        items.add("French's ");
        items.add("French's ");
        items.add("French's ");
        items.add("French's ");
        items.add("French's ");
        items.add("French's ");
        items.add("Freschetta ");
        items.add("Freschetta ");
        items.add("Freschetta ");
        items.add("Freschetta ");
        items.add("Freschetta ");
        items.add("Freschetta ");
        items.add("Friends");
        items.add("Friendship ");
        items.add("Friendship ");
        items.add("Friendship ");
        items.add("Fun Delina");
        items.add("Fun Delina");
        items.add("G Hughes");
        items.add("G Hughes");
        items.add("G Hughes");
        items.add("G Hughes");
        items.add("G Hughes");
        items.add("G Hughes");
        items.add("G Hughes ");
        items.add("Gaspars ");
        items.add("Gaspars ");
        items.add("Geisha");
        items.add("Gerardo's Trattoria Amalfi");
        items.add("Gerardo's Trattoria Amalfi");
        items.add("Gerardo's Trattoria Amalfi");
        items.add("Gillian's ");
        items.add("Giosanmi Rama ");
        items.add("Giosanmi Rama ");
        items.add("Giosanmi Rama ");
        items.add("Giosanmi Rama ");
        items.add("Giosanmi Rama ");
        items.add("Giosanmi Rama ");
        items.add("Giosanmi Rama ");
        items.add("Giosanmi Rama ");
        items.add("Giosanmi Rama ");
        items.add("Godshalls");
        items.add("GoGo Squeez ");
        items.add("Gold Peak Tea");
        items.add("Gold Peak Tea");
        items.add("Gold Peak Tea");
        items.add("Gold Peak Tea");
        items.add("Gold Peak Tea");
        items.add("Gold Peak Tea");
        items.add("Gold Peak Tea");
        items.add("Gold Peak Tea");
        items.add("Gold Peak Tea");
        items.add("Gold Peak Tea");
        items.add("Gold Peak Tea");
        items.add("Gold Peak Tea");
        items.add("Gold Peak Tea");
        items.add("Gold Peak Tea");
        items.add("Gold Seasons");
        items.add("Gold Seasons");
        items.add("Gold Seasons");
        items.add("Gold Seasons");
        items.add("Golden ");
        items.add("Golden ");
        items.add("Golden ");
        items.add("Golden Curry");
        items.add("Golden Curry");
        items.add("Goobers ");
        items.add("Good Food Made ");
        items.add("Good Food Made ");
        items.add("Good Food Made ");
        items.add("Good Food Made ");
        items.add("Good Food Made ");
        items.add("Goodbelly");
        items.add("Goodbelly");
        items.add("Goodbelly");
        items.add("Goodbelly");
        items.add("Goodbelly");
        items.add("Gordon's ");
        items.add("Gorton's ");
        items.add("Gorton's ");
        items.add("Grandmother's ");
        items.add("Grandmother's ");
        items.add("Grando's");
        items.add("Grando's");
        items.add("Green Leaf Brand");
        items.add("Green valley ");
        items.add("Green Valley ");
        items.add("Green Valley ");
        items.add("Green Valley ");
        items.add("Green Valley ");
        items.add("Gulden's ");
        items.add("Gulf Pacific");
        items.add("Gulf Pacific");
        items.add("Gulf Wax");
        items.add("Gummi Factory");
        items.add("Gunters");
        items.add("Half Baked ");
        items.add("Half Baked ");
        items.add("Handover ");
        items.add("Handover ");
        items.add("Happy Kid ");
        items.add("Happy Kid ");
        items.add("Healthy Ones ");
        items.add("Healthy Ones ");
        items.add("Healthy Ones ");
        items.add("Heath");
        items.add("Heinz ");
        items.add("Heinz ");
        items.add("Heinz ");
        items.add("Heinz ");
        items.add("Heinz ");
        items.add("Heinz ");
        items.add("Heinz ");
        items.add("Heinz ");
        items.add("Heinz ");
        items.add("Heinz ");
        items.add("Heinz ");
        items.add("Heinz ");
        items.add("Heinz ");
        items.add("Hellmann's ");
        items.add("Hellmann's ");
        items.add("Hellmann's ");
        items.add("Hellmann's ");
        items.add("Hellmann's ");
        items.add("Hellmann's ");
        items.add("Hellmann's ");
        items.add("Hellmann's ");
        items.add("Hellmann's ");
        items.add("Hero ");
        items.add("Hero ");
        items.add("Hi-CHew");
        items.add("Hi-Chew");
        items.add("Hillshire Farm ");
        items.add("Hillshire Farm ");
        items.add("Hillshire Farm ");
        items.add("Hillshire Farm ");
        items.add("Hillshire Farm ");
        items.add("Hillshire Farm ");
        items.add("Hillshire Farm ");
        items.add("Hillshire Farm ");
        items.add("Hillshire Farm ");
        items.add("Hillshire Farm ");
        items.add("Hint");
        items.add("Hint");
        items.add("Hint");
        items.add("Hint");
        items.add("Hint");
        items.add("Hint");
        items.add("Hint");
        items.add("Hint");
        items.add("Hint");
        items.add("Hint");
        items.add("Hoilday ");
        items.add("Holland House ");
        items.add("Holland House ");
        items.add("Holland House ");
        items.add("Holland House ");
        items.add("Holland House ");
        items.add("Holland House ");
        items.add("Home Run Inn");
        items.add("Home Run Inn");
        items.add("Home Run Inn");
        items.add("Home Style ");
        items.add("Homestyle");
        items.add("Honeycup ");
        items.add("Hood ");
        items.add("Hormel ");
        items.add("Hormel ");
        items.add("Hormel ");
        items.add("Hormel ");
        items.add("Hormel ");
        items.add("Hormel ");
        items.add("Hormel ");
        items.add("Hormel ");
        items.add("Hormel ");
        items.add("Hormel ");
        items.add("Hormel ");
        items.add("Hormel ");
        items.add("House of Pasta");
        items.add("House Of Tsang ");
        items.add("House Of Tsang ");
        items.add("House Of Tsang ");
        items.add("House Of Tsang ");
        items.add("Howard's ");
        items.add("Howard's ");
        items.add("Howard's ");
        items.add("Howard's ");
        items.add("HP");
        items.add("Huy Fong");
        items.add("Huy Fong");
        items.add("Huy Fong");
        items.add("Icelandic ");
        items.add("Icelandic ");
        items.add("Icelandic ");
        items.add("Icelandic ");
        items.add("Icelandic ");
        items.add("Icelandic ");
        items.add("Incogmeato ");
        items.add("Incogmeato ");
        items.add("Incogmeato ");
        items.add("inglehoffer");
        items.add("inglehoffer");
        items.add("Italica");
        items.add("Italica");
        items.add("Italica");
        items.add("Italica ");
        items.add("Italica ");
        items.add("Italica ");
        items.add("Italica ");
        items.add("Italica ");
        items.add("Italica ");
        items.add("J.J. Nissen");
        items.add("James Killer & Son");
        items.add("Jelly Knife ");
        items.add("Jenni-O");
        items.add("Jenni-O");
        items.add("Jenni-O");
        items.add("Jenni-O");
        items.add("Jenni-O");
        items.add("Jenni-O");
        items.add("Jet puffed");
        items.add("JHL");
        items.add("Jiffy ");
        items.add("Jimmy Dean ");
        items.add("Jimmy Dean ");
        items.add("Jimmy Dean ");
        items.add("Jimmy Dean ");
        items.add("Jimmy Dean ");
        items.add("Jimmy Dean ");
        items.add("Jimmy Dean ");
        items.add("Jimmy Dean ");
        items.add("Jimmy Dean ");
        items.add("JimmyDean");
        items.add("JimmyDean");
        items.add("JimmyDean");
        items.add("JimmyDean");
        items.add("JimmyDean");
        items.add("JimmyDean");
        items.add("John McCann's");
        items.add("John Morrell");
        items.add("Jolly Time ");
        items.add("Jolly Time ");
        items.add("Jolly Time ");
        items.add("Jordans");
        items.add("Jordans ");
        items.add("Joy ");
        items.add("Joy ");
        items.add("Joy ");
        items.add("Joy ");
        items.add("Joy ");
        items.add("Joy ");
        items.add("Joy ");
        items.add("Joy ");
        items.add("Joyce Chen ");
        items.add("Joyce Chen ");
        items.add("Joyce Chen ");
        items.add("Joyva");
        items.add("Justin's");
        items.add("Kadoya");
        items.add("Kahiki");
        items.add("Kahiki");
        items.add("Kahiki");
        items.add("Kahiki");
        items.add("Kahiki");
        items.add("Karma");
        items.add("Karma");
        items.add("Karma");
        items.add("Karma");
        items.add("Karma");
        items.add("Karma");
        items.add("Kashi ");
        items.add("Kashi ");
        items.add("Katz");
        items.add("Katz");
        items.add("Katz");
        items.add("Kayem ");
        items.add("Kayem ");
        items.add("Kayem ");
        items.add("Kayem ");
        items.add("Kayem ");
        items.add("Kayem ");
        items.add("Kayem ");
        items.add("Kayem ");
        items.add("Kayem ");
        items.add("Kayem ");
        items.add("Kayem ");
        items.add("Kayem ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Kellogg's ");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Ken's Steak House");
        items.add("Kikkoman ");
        items.add("Kikkoman ");
        items.add("Kikkoman ");
        items.add("Kikkoman ");
        items.add("Kikkoman ");
        items.add("Kikkoman ");
        items.add("Kikkoman ");
        items.add("Kikkoman ");
        items.add("Kikkoman ");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind");
        items.add("Kind ");
        items.add("Kind ");
        items.add("Kind ");
        items.add("Kitchen & Love");
        items.add("Kitchen & Love");
        items.add("Kitchen & Love");
        items.add("Kitchen & Love");
        items.add("Kitchen & Love");
        items.add("Kitchen & Love");
        items.add("kitchen of love Cucina & Amore");
        items.add("kitchen of love Cucina & Amore");
        items.add("kitchen of love Cucina & Amore");
        items.add("Kitchens Of India");
        items.add("Kitchens Of India");
        items.add("Kitchens Of India");
        items.add("Kitchens Of India");
        items.add("Kitchens Of India");
        items.add("Kitchens Of India");
        items.add("Kitchens Of India");
        items.add("Kitchens Of India");
        items.add("Kitchens Of India");
        items.add("Kitchens Of India");
        items.add("Kite hill");
        items.add("Kite hill");
        items.add("Kite hill");
        items.add("Kite hill");
        items.add("Kitkat ");
        items.add("Kitkat ");
        items.add("Kitkat ");
        items.add("Kodaik Cakes ");
        items.add("Kodaik Cakes ");
        items.add("Kosciusko ");
        items.add("Krinos ");
        items.add("Krinos ");
        items.add("Krinos ");
        items.add("Krinos ");
        items.add("L & A");
        items.add("La Choy ");
        items.add("La Choy ");
        items.add("La Choy ");
        items.add("La Choy ");
        items.add("La Spagnola ");
        items.add("La Spagnola ");
        items.add("La Spagnola ");
        items.add("La Spagnola ");
        items.add("La Spagnola ");
        items.add("La Tourangelle ");
        items.add("La Tourangelle ");
        items.add("La Yogurt");
        items.add("Laforestiere");
        items.add("Lawry's ");
        items.add("Lawry's ");
        items.add("Lawry's ");
        items.add("Lawry's ");
        items.add("Lawry's ");
        items.add("Lawry's ");
        items.add("Lawry's ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lean Cuisine ");
        items.add("Lee Kum Kee");
        items.add("Leidys ");
        items.add("Leidys ");
        items.add("Leidys ");
        items.add("Leidys ");
        items.add("Lender's ");
        items.add("Lender's ");
        items.add("Lender's ");
        items.add("Lender's ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant ");
        items.add("Levant  ");
        items.add("Levant  ");
        items.add("Life Cuisine ");
        items.add("Life Cuisine ");
        items.add("Life Cuisine ");
        items.add("Life Cuisine ");
        items.add("Life Cuisine ");
        items.add("Life Cuisine ");
        items.add("Lily's");
        items.add("Lily's");
        items.add("Lily's ");
        items.add("Lily's ");
        items.add("Lindsay ");
        items.add("Lindsay ");
        items.add("LLL S No Style ");
        items.add("LLL S No Style ");
        items.add("London Pub ");
        items.add("Lucini");
        items.add("Lucini");
        items.add("Lucini");
        items.add("Lucini");
        items.add("Lucini");
        items.add("Lucini");
        items.add("Lucio");
        items.add("Lucio");
        items.add("Lucio");
        items.add("Lucio");
        items.add("Lucio");
        items.add("Lucio");
        items.add("Lucio");
        items.add("Lympiana ");
        items.add("Yo Crunch");
        items.add("Made Good");
        items.add("Made Good");
        items.add("Lilly B's");
        items.add("Lilly B's");
        items.add("Madhava");
        items.add("Madhava");
        items.add("Malt O Meal");
        items.add("Malt O Meal");
        items.add("Malt O Meal");
        items.add("Malt O Meal");
        items.add("Malt O Meal");
        items.add("Malt O Meal");
        items.add("Malt O Meal");
        items.add("Malt O Meal");
        items.add("Malt O Meal");
        items.add("Malt O Meal");
        items.add("Mama Mancini's ");
        items.add("Mama Mancini's ");
        items.add("Mama Marys");
        items.add("Mama Marys");
        items.add("Mama Marys");
        items.add("Mancini ");
        items.add("Manwich ");
        items.add("Manwich ");
        items.add("Manwich ");
        items.add("Manzola");
        items.add("Manzola");
        items.add("Manzola");
        items.add("Mappleglazed ");
        items.add("Maranatha");
        items.add("Maranatha");
        items.add("Maranatha");
        items.add("Maranatha");
        items.add("Maranatha ");
        items.add("Marconi ");
        items.add("Marconi ");
        items.add("Mariokart ");
        items.add("Mariokart ");
        items.add("Mariokart ");
        items.add("Mariokart ");
        items.add("Mariokart ");
        items.add("Mariokart ");
        items.add("Mariokart ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Market Basket ");
        items.add("Marukan ");
        items.add("Marukan ");
        items.add("Marukan ");
        items.add("Marukan ");
        items.add("Maypo");
        items.add("Mc Cocktail ");
        items.add("McCann's ");
        items.add("Mee Tu ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Mezzetta ");
        items.add("Michael Angelo's");
        items.add("Michael Angelo's");
        items.add("Michael Angelo's");
        items.add("Michael Angelo's");
        items.add("Mike and ike");
        items.add("MilDer ");
        items.add("Minute maid");
        items.add("Minute maid");
        items.add("Miracle Whip ");
        items.add("Miracle Whip ");
        items.add("Mister Mustard ");
        items.add("Modenaceti ");
        items.add("Mon Ami");
        items.add("Morning Stars Farms ");
        items.add("Morning Stars Farms ");
        items.add("Morning Stars Farms ");
        items.add("Morning Stars Farms ");
        items.add("Morning Stars Farms ");
        items.add("Morning Stars Farms ");
        items.add("Morning Stars Farms ");
        items.add("Morning Stars Farms ");
        items.add("Morning Stars Farms ");
        items.add("Morning Stars Farms ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mott's ");
        items.add("Mounds ");
        items.add("Mrs Cubbison's ");
        items.add("Mrs Cubbison's ");
        items.add("Mrs Cubbison's ");
        items.add("Mrs Cubbison's ");
        items.add("Mrs Cubbison's ");
        items.add("Mrs Cubbison's ");
        items.add("Mrs Fanning's");
        items.add("Mrs Fanning's");
        items.add("Mrs. Butter Worth's");
        items.add("Mrs. Butter Worth's");
        items.add("Mrs.Paul's");
        items.add("Mrs.Paul's");
        items.add("Mrs.T's ");
        items.add("Mrs.T's ");
        items.add("Mrs.T's ");
        items.add("Mrs.T's ");
        items.add("Mrs.T's ");
        items.add("Mrs.T's ");
        items.add("Murry's ");
        items.add("Murry's ");
        items.add("Musselman's ");
        items.add("Musselman's ");
        items.add("Musselman's ");
        items.add("Musselman's ");
        items.add("Mystic Pizza ");
        items.add("Mystic Pizza ");
        items.add("Mystic Pizza ");
        items.add("Nature Nates");
        items.add("Nature Nates");
        items.add("Nature Nates");
        items.add("Nature Nates");
        items.add("Nature Valley");
        items.add("Nature Valley");
        items.add("Nature Valley");
        items.add("Nature Valley");
        items.add("Nature Valley");
        items.add("Nature Valley");
        items.add("Nature Valley");
        items.add("Nature's Path ");
        items.add("Nature's Path ");
        items.add("Nature's Path ");
        items.add("Nature's Path ");
        items.add("Nature's Path ");
        items.add("Nature's Path ");
        items.add("Nature's Path ");
        items.add("Nature's Path ");
        items.add("Nature's Path ");
        items.add("Nature's Path ");
        items.add("Nature's Path ");
        items.add("Nature's Path ");
        items.add("Nature's Path ");
        items.add("Nature's Path ");
        items.add("Nature's Path ");
        items.add("Near East ");
        items.add("Near East ");
        items.add("Near East ");
        items.add("Near East ");
        items.add("Near East ");
        items.add("Near East ");
        items.add("Near East ");
        items.add("Near East ");
        items.add("Near East ");
        items.add("Near East ");
        items.add("Near East ");
        items.add("Near East ");
        items.add("Near East ");
        items.add("Near East ");
        items.add("Near East ");
        items.add("Neuro Sonic");
        items.add("Neuro Sonic");
        items.add("Neuro Sonic");
        items.add("NewBridge ");
        items.add("Newman's Own ");
        items.add("Newman's Own ");
        items.add("Newman's Own ");
        items.add("Newman's Own ");
        items.add("Newman's Own ");
        items.add("Newman's Own ");
        items.add("Newman's Own ");
        items.add("Newman's Own ");
        items.add("Newman's Own ");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("Newmen's Own");
        items.add("NewYork Bakery");
        items.add("NewYork Bakery");
        items.add("Noosa ");
        items.add("Noosa ");
        items.add("Noosa ");
        items.add("Noosa ");
        items.add("Noosa ");
        items.add("North Country ");
        items.add("North Country ");
        items.add("North Country ");
        items.add("North Country ");
        items.add("North Country ");
        items.add("North Country ");
        items.add("North Country ");
        items.add("North Country ");
        items.add("Nut Butter Rx");
        items.add("Nut Butter Rx");
        items.add("Nut Butter Rx");
        items.add("Nutiva ");
        items.add("Nutiva ");
        items.add("Old Neighborhood ");
        items.add("Old Neighborhood ");
        items.add("Old Neighborhood ");
        items.add("Old Neighborhood ");
        items.add("Old Neighborhood ");
        items.add("Old Neighborhood ");
        items.add("Old Neighborhood ");
        items.add("Old Neighborhood ");
        items.add("Olivari ");
        items.add("Olivari ");
        items.add("Olivari ");
        items.add("Olive Garden ");
        items.add("Olive Garden ");
        items.add("Once Up on Farm");
        items.add("Organic Baby Food");
        items.add("Organic Baby Food");
        items.add("Organic Baby Food");
        items.add("Organic Baby Food ");
        items.add("Organic Supwefoods ");
        items.add("Organic Supwefoods ");
        items.add("Organic Supwefoods ");
        items.add("Organic Supwefoods ");
        items.add("Organic Ville");
        items.add("Organic Ville");
        items.add("Organic Ville");
        items.add("Organic Ville");
        items.add("Orville Redenbacher's ");
        items.add("Orville Redenbacher's ");
        items.add("Orville Redenbacher's ");
        items.add("Orville Redenbacher's ");
        items.add("Orville Redenbacher's ");
        items.add("Oscar Mayer ");
        items.add("Oscar Mayer ");
        items.add("Oscar Mayer ");
        items.add("Oscar Mayer ");
        items.add("Oscar Mayer ");
        items.add("Oscar Mayer ");
        items.add("Oscar Mayer ");
        items.add("Oscar Mayer ");
        items.add("Oscar Mayer ");
        items.add("Oscar Mayer ");
        items.add("Oscar Mayer ");
        items.add("Outsiders Pizza Company ");
        items.add("Outsiders Pizza Company ");
        items.add("P.F.Chang's");
        items.add("P.F.Chang's");
        items.add("P.F.Chang's");
        items.add("P.F.Chang's");
        items.add("P.F.Chang's");
        items.add("P.F.Chang's");
        items.add("P.F.Chang's");
        items.add("P.F.Chang's");
        items.add("P.F.Chang's");
        items.add("P.F.Chang's");
        items.add("P.F.Chang's");
        items.add("Paesana");
        items.add("Paesana");
        items.add("Paesana");
        items.add("Paesana");
        items.add("Paesana");
        items.add("Paesana");
        items.add("Paesana");
        items.add("Paesana");
        items.add("Paesana");
        items.add("Paesana");
        items.add("Paesana");
        items.add("Paesana");
        items.add("Pam ");
        items.add("Pam ");
        items.add("Pam ");
        items.add("Pampeano ");
        items.add("Panda ");
        items.add("Papa Gino's Pizzeria ");
        items.add("Papa Gino's Pizzeria ");
        items.add("Pastabilities");
        items.add("Pastabilities");
        items.add("Pastabilities");
        items.add("Peanut Butter & co");
        items.add("Peanut Butter & co");
        items.add("Peanut Butter & co");
        items.add("Peanut Butter & co");
        items.add("Pearls ");
        items.add("Pearls ");
        items.add("Pearls ");
        items.add("Pearls ");
        items.add("Pearls ");
        items.add("Pearls ");
        items.add("Pearls ");
        items.add("Pearls ");
        items.add("Pearls ");
        items.add("Pearls ");
        items.add("Pearls ");
        items.add("Pearls ");
        items.add("Pearls ");
        items.add("Pearls ");
        items.add("Pearls ");
        items.add("Pearls ");
        items.add("Peppermint Cobalt");
        items.add("Pickapeppa ");
        items.add("Pierre Drive Thru");
        items.add("Pierre Drive Thru");
        items.add("Pillars");
        items.add("Pillars");
        items.add("Pirro's");
        items.add("Pirro's");
        items.add("Plant Made ");
        items.add("Plant Made ");
        items.add("Plant Made ");
        items.add("Plant Made ");
        items.add("Plant Made ");
        items.add("Plant Made ");
        items.add("Pompeian ");
        items.add("Pompeian ");
        items.add("Pompeian ");
        items.add("Pompeian ");
        items.add("Pop Secret ");
        items.add("Pop Secret ");
        items.add("Pop Secret ");
        items.add("Pop Secret ");
        items.add("Pop Secret ");
        items.add("Pop Secret ");
        items.add("Pop Secret ");
        items.add("Pop Secret ");
        items.add("Pop Secret ");
        items.add("Pop Secret ");
        items.add("Pop Secret ");
        items.add("Pop Secret ");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Pop Tarts");
        items.add("Poppy's ");
        items.add("Poppy's ");
        items.add("Poppy's ");
        items.add("Poppy's ");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Post");
        items.add("Premier Protien ");
        items.add("Premier Protien ");
        items.add("Premier Protien ");
        items.add("Premier Protien ");
        items.add("Premier Protien ");
        items.add("Premier Protien ");
        items.add("Premium Gold");
        items.add("Pulmuone");
        items.add("Pulmuone");
        items.add("Pulmuone");
        items.add("Pure Farmland ");
        items.add("Pure Farmland ");
        items.add("Pure Leaf ");
        items.add("Pure Leaf ");
        items.add("Pure Leaf ");
        items.add("Purely Elizabeth");
        items.add("Purely Elizabeth");
        items.add("Purely Elizabeth");
        items.add("Purely Elizabeth");
        items.add("Purely Elizabeth");
        items.add("Purely Elizabeth");
        items.add("Purely Elizabeth");
        items.add("Purely Elizabeth ");
        items.add("Quaker ");
        items.add("Quaker ");
        items.add("Quaker ");
        items.add("Quaker ");
        items.add("Quaker ");
        items.add("Quaker ");
        items.add("Quaker ");
        items.add("Quaker ");
        items.add("Quaker ");
        items.add("Quaker ");
        items.add("Quaker ");
        items.add("Quaker ");
        items.add("Quaker ");
        items.add("Quaker ");
        items.add("Quaker ");
        items.add("Quality Farms ");
        items.add("Quality Farms ");
        items.add("Quattro Formaggio ");
        items.add("R.W. Knudsen");
        items.add("R.W. Knudsen");
        items.add("R.W. Knudsen");
        items.add("R.W. Knudsen");
        items.add("R.W. Knudsen");
        items.add("R.W. Knudsen");
        items.add("R.W. Knudsen");
        items.add("R.W. Knudsen");
        items.add("R.W. Knudsen");
        items.add("R.W. Knudsen");
        items.add("R.W. Knudsen");
        items.add("R.W. Knudsen");
        items.add("Raisinets ");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Rao's");
        items.add("Ratio Kito ");
        items.add("Ratio Kito ");
        items.add("Ray's ");
        items.add("Ray's ");
        items.add("Really Raw");
        items.add("Red Baron ");
        items.add("Red Baron ");
        items.add("Red Baron ");
        items.add("Red Baron ");
        items.add("Red Baron ");
        items.add("Red Baron ");
        items.add("RedHot ");
        items.add("RedHot ");
        items.add("Rhodes");
        items.add("Rhodes");
        items.add("Rhodes");
        items.add("Rhodes");
        items.add("Rhodes");
        items.add("Rhodes");
        items.add("Rice Roni");
        items.add("Rice Roni");
        items.add("Rice Roni");
        items.add("Rice Roni");
        items.add("Rice Roni");
        items.add("Rice Roni");
        items.add("Rice Roni");
        items.add("Rice Roni");
        items.add("Rice Roni");
        items.add("Rice Roni");
        items.add("Rice Select");
        items.add("Rice Select");
        items.add("Rice Select");
        items.add("Rice Select");
        items.add("Rice Select");
        items.add("Rice Select");
        items.add("Rice Select");
        items.add("Rice Select");
        items.add("Rice Select");
        items.add("Rice Select");
        items.add("Richard's");
        items.add("Riesa");
        items.add("Riesa");
        items.add("Riesa");
        items.add("Riesa");
        items.add("Rips");
        items.add("Rips");
        items.add("Rao's");
        items.add("Robert  Rothschid ");
        items.add("Roland ");
        items.add("Romanoff ");
        items.add("Romanoff ");
        items.add("Romanoff ");
        items.add("Romanoff ");
        items.add("Rosetto");
        items.add("Rosetto");
        items.add("Rosetto");
        items.add("Rothbury Farms ");
        items.add("Rothbury Farms ");
        items.add("Rothbury Farms ");
        items.add("Rothbury Farms ");
        items.add("Rubinstein's ");
        items.add("Rubinstein's ");
        items.add("Russell Stover ");
        items.add("Russell Stover ");
        items.add("Russell Stover ");
        items.add("RX");
        items.add("RX");
        items.add("RX");
        items.add("RX");
        items.add("RX");
        items.add("RX");
        items.add("RX");
        items.add("Sable and Rosenfeld");
        items.add("Sable and Rosenfeld");
        items.add("Saffron Road");
        items.add("Saffron Road");
        items.add("Saffron Road");
        items.add("Saffron Road");
        items.add("Sambal Oelex");
        items.add("Sambal Oelex");
        items.add("San Remo");
        items.add("Sander's ");
        items.add("Sander's ");
        items.add("Sander's ");
        items.add("Sandwich Bros");
        items.add("Sandwich Bros ");
        items.add("Sandwich Bros ");
        items.add("Sandwich Bros ");
        items.add("Santorina ");
        items.add("Saucy Susar ");
        items.add("Screamin' Sicilian ");
        items.add("Screamin' Sicilian ");
        items.add("Screamin' Sicilian ");
        items.add("Screamin' Sicilian ");
        items.add("Sell's");
        items.add("Silver Floss ");
        items.add("Skinny girl ");
        items.add("Skinny girl ");
        items.add("Skinny girl ");
        items.add("Skinny girl ");
        items.add("Sky Lark ");
        items.add("Smash ");
        items.add("So Be Water");
        items.add("Sonoma Flatbreads ");
        items.add("Sonoma Flatbreads ");
        items.add("Soup Singles");
        items.add("Soup Singles");
        items.add("Soup Singles");
        items.add("Southern Comfort");
        items.add("Southwestern Veggie ");
        items.add("Soy Yay ");
        items.add("Sparta ");
        items.add("Sparta ");
        items.add("Spearmint Rain");
        items.add("St. Dalfour ");
        items.add("St. Dalfour ");
        items.add("Sticky");
        items.add("Sticky");
        items.add("Sticky");
        items.add("STOK");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stouffer's ");
        items.add("Stove Top ");
        items.add("Stove Top ");
        items.add("Stove Top ");
        items.add("Stove Top ");
        items.add("Stove Top ");
        items.add("Stove Top ");
        items.add("Straight Up Tea");
        items.add("Straight Up Tea");
        items.add("Straight Up Tea");
        items.add("Straight Up Tea");
        items.add("Straight Up Tea");
        items.add("Straight Up Tea");
        items.add("Stuffed Foods");
        items.add("Stuffed Foods");
        items.add("Stuffed Foods");
        items.add("Success");
        items.add("Success");
        items.add("Success");
        items.add("Success");
        items.add("Success");
        items.add("Success");
        items.add("Success");
        items.add("Success");
        items.add("Sugardale");
        items.add("Sugardale ");
        items.add("Sugardale ");
        items.add("Sun Butter ");
        items.add("Sun Butter ");
        items.add("Sun Butter ");
        items.add("Sun Butter ");
        items.add("Sun Luck");
        items.add("Sun Luck");
        items.add("Sun Luck");
        items.add("Sun Luck");
        items.add("Sun Luck");
        items.add("Sun Luck ");
        items.add("Sun Luck ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Sunbelt Bakery ");
        items.add("Super Food");
        items.add("Super Food");
        items.add("Supper Pretzel");
        items.add("Sure Jell ");
        items.add("Sure Jell ");
        items.add("Sushi Chef ");
        items.add("Swanson ");
        items.add("Swanson ");
        items.add("Sweet Earth ");
        items.add("Sweet Earth ");
        items.add("Tabasco ");
        items.add("Tabasco ");
        items.add("Tabasco ");
        items.add("Tabasco ");
        items.add("TAI & PEI");
        items.add("TAI & PEI");
        items.add("TAI & PEI");
        items.add("TAI & PEI");
        items.add("TAI & PEI");
        items.add("TAI & PEI");
        items.add("TAI & PEI");
        items.add("TAI & PEI");
        items.add("TAI & PEI");
        items.add("Tamari ");
        items.add("Tamari ");
        items.add("Tamari ");
        items.add("Taza ");
        items.add("Taza ");
        items.add("Taza ");
        items.add("Taza ");
        items.add("Taza ");
        items.add("Teas Tea Organic ");
        items.add("Teas Tea Organic ");
        items.add("Teas Tea Organic ");
        items.add("Teras ");
        items.add("Teras ");
        items.add("Teras ");
        items.add("Tessera ");
        items.add("TGI Fridays");
        items.add("TGI Fridays");
        items.add("TGI Fridays");
        items.add("TGI Fridays");
        items.add("TGI Fridays");
        items.add("TGI Fridays");
        items.add("Thai Kictchen ");
        items.add("Thai Kitchen ");
        items.add("Thai Kitchen ");
        items.add("Thai Kitchen ");
        items.add("The Alpha ");
        items.add("The Alpha ");
        items.add("The Ginger People ");
        items.add("Tic Tac ");
        items.add("Tic Tac ");
        items.add("Tiger ");
        items.add("Toffifay");
        items.add("Tofutti");
        items.add("Tony's ");
        items.add("Tony's ");
        items.add("Tony's ");
        items.add("Tresca");
        items.add("Tresca");
        items.add("Tresca");
        items.add("Trimino");
        items.add("Trimino");
        items.add("Trimino");
        items.add("Trimino");
        items.add("Trimona");
        items.add("Tripple Leaf Brand");
        items.add("Tropical ");
        items.add("Tropical ");
        items.add("Tropical ");
        items.add("Tropical ");
        items.add("Tropical ");
        items.add("Truwhip ");
        items.add("Truwhip ");
        items.add("Two Good");
        items.add("Two Good");
        items.add("Two Good");
        items.add("Two Good");
        items.add("Two Good");
        items.add("Two Good");
        items.add("Two Good");
        items.add("Two Good");
        items.add("Two Good");
        items.add("Two Good");
        items.add("Two Good");
        items.add("Two Good");
        items.add("Tyling ");
        items.add("Uncle Matt's");
        items.add("Uncle Matt's");
        items.add("Uncle Sam");
        items.add("Uncle Sam");
        items.add("Underwood");
        items.add("Underwood");
        items.add("Unreal");
        items.add("Unreal");
        items.add("Unreal");
        items.add("Unreal");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("V8");
        items.add("Van's ");
        items.add("Van's ");
        items.add("Vermont Maid ");
        items.add("Vermont Maid ");
        items.add("Victoria");
        items.add("Victoria");
        items.add("Victoria");
        items.add("Victoria");
        items.add("Victorina ");
        items.add("Viet Huong");
        items.add("Virginia Brand ");
        items.add("Vitamin 1");
        items.add("Vitamin 1");
        items.add("Vitamin 1");
        items.add("Vitamin 1");
        items.add("Vitamin Water");
        items.add("Vitamin Water");
        items.add("Vitamin Water");
        items.add("Vitamin Water");
        items.add("Vitamin Water");
        items.add("Vitamin Water");
        items.add("Vitamin Water");
        items.add("Vitamin Water");
        items.add("Vitamin Water");
        items.add("Vitamin Water");
        items.add("Vitamin Water");
        items.add("Vitamin Water");
        items.add("Vlasic ");
        items.add("Vlasic ");
        items.add("Vlasic ");
        items.add("Vlasic ");
        items.add("Vlasic ");
        items.add("Vlasic ");
        items.add("Vlasic ");
        items.add("Vlasic ");
        items.add("Walden farms");
        items.add("Walden farms");
        items.add("Walden Farms ");
        items.add("Walden Farms ");
        items.add("Walden Farms ");
        items.add("Walden Farms ");
        items.add("Walden Farms ");
        items.add("Waterhill");
        items.add("Waterhill");
        items.add("Waterhill");
        items.add("Waterhill ");
        items.add("Wee Bee Honey");
        items.add("Weetabix");
        items.add("Werther's");
        items.add("Werther's");
        items.add("When Pig's Fly");
        items.add("When Pig's Fly");
        items.add("When Pig's Fly");
        items.add("When Pig's Fly");
        items.add("When Pig's Fly");
        items.add("Wholesome");
        items.add("Wicked Toisted ");
        items.add("Wickles ");
        items.add("Wickles ");
        items.add("Wild Friends ");
        items.add("Wild Mike's");
        items.add("Wild Mike's ");
        items.add("Wild Mike's ");
        items.add("Wiley Wallaby");
        items.add("Wisconsin's Finest");
        items.add("Wisconsin's Finest");
        items.add("Wisconsin's Finest");
        items.add("Wisconsin's Finest");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wish Bone");
        items.add("Wood Stocks");
        items.add("Wood Stocks");
        items.add("Woodstock");
        items.add("Woodstock");
        items.add("Woodstock ");
        items.add("Woodstock ");
        items.add("Woodstock ");
        items.add("Woodstock ");
        items.add("Woodstock ");
        items.add("World Harbors ");
        items.add("World Harbors ");
        items.add("World Harbors ");
        items.add("World Harbors ");
        items.add("World Harbors ");
        items.add("World Harbors ");
        items.add("World Harbors ");
        items.add("World Harbors ");
        items.add("World Harbors ");
        items.add("World Harbors ");
        items.add("World Harbors ");
        items.add("World Harbors ");
        items.add("World Harbors ");
        items.add("World Harbors ");
        items.add("Wow Butter");
        items.add("Wrigley's ");
        items.add("Wrigley's ");
        items.add("Wrigley's ");
        items.add("Wrigley's ");
        items.add("Wrigley's ");
        items.add("Wrigley's ");
        items.add("Yoohoo");
        items.add("Zatarains");
        items.add("Zatarains");
        items.add("Zatarains");
        items.add("Zatarains");
        items.add("Zatarains");
        items.add("Zatarains");
        items.add("Zatarains");
        items.add("Zatarains");
        items.add("Zeppy");
        items.add("Zeppy");
        items.add("Zeppy");
        items.add("Zeppy");
        items.add("Zeppy");
        items.add("Zeppy");
        items.add("Zeppy");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm");
        items.add("Richarson's Farm ");


        System.out.println("---FINAL ITEMS");
        items.forEach(System.out::println);
        System.out.println("---FINAL ITEMS SIZE "+ items.size());



    }
}
